const productPricing: Array<any> = [
  {
    id: 1,
    postalCode: 33566,
    city: 'Plant City',
    territory: 'Tampa',
    state: 'Florida',
    stateAbbreviation: 'FL',
    needsPermit: true,
    isFranchise: false,
    products: [
      {
        sku: 'RO10',
        price: 499,
        debris: ['Construction', 'Household', 'Mix', 'Concrete'],
        discountedPrice: 459,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 7,
      },
      {
        sku: 'RO20',
        price: 599,
        debris: ['Construction', 'Household', 'Mix', 'Concrete'],
        discountedPrice: 559,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'RO30',
        price: 699,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 659,
        available: false,
        category: 'Rolloff',
        includedWeight: 3000,
        maxRentalPeriod: 14,
      },
    ],
  },
  {
    id: 2,
    postalCode: 33602,
    city: 'Tampa',
    territory: 'Tampa',
    state: 'Florida',
    stateAbbreviation: 'FL',
    needsPermit: true,
    permitFee: 120,
    permitNotes: 'Permit only valid for 3 days. Prescheduled pickup required',
    isFranchise: true,
    franchisePercentage: 0.1,
    products: [
      {
        sku: 'RO20',
        price: 499,
        debris: ['Construction', 'Household', 'Mix', 'Concrete'],
        discountedPrice: 459,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'RO30',
        price: 599,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 549,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'BIN8',
        price: 299,
        debris: ['Office', 'Food', 'Mix'],
        discountedPrice: 199,
        available: true,
        category: 'Bin',
        includedWeight: '',
        maxRentalPeriod: '',
      },
    ],
  },
]

export default productPricing
