const productPricing: Array<any> = [
  {
    id: 1,
    postalCode: 33566,
    city: 'Plant City',
    territory: 'Tampa',
    state: 'Florida',
    stateAbbreviation: 'FL',
    needsPermit: false,
    permitFee: 0,
    permitNotes: '',
    isFranchise: false,
    franchisePercentage: 0.0,
    overagePercentage: 0.069,
    products: [
      {
        sku: 'RO10',
        price: 499,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 459,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 7,
      },
      {
        sku: 'RO20',
        price: 599,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 559,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'RO20C',
        price: 699,
        debris: ['Concrete'],
        discountedPrice: 669,
        available: true,
        category: 'Rolloff',
        includedWeight: 16000,
        maxRentalPeriod: 14,
      },

      {
        sku: 'RO30',
        price: 699,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 659,
        available: false,
        category: 'Rolloff',
        includedWeight: 3000,
        maxRentalPeriod: 14,
      },
    ],
  },
  {
    id: 2,
    postalCode: 33602,
    city: 'Tampa',
    territory: 'Tampa',
    state: 'Florida',
    stateAbbreviation: 'FL',
    needsPermit: true,
    permitFee: 120,
    permitNotes: 'Permit only valid for 3 days. Prescheduled pickup required',
    isFranchise: true,
    franchisePercentage: 0.1,
    overagePercentage: 0.069,
    products: [
      {
        sku: 'RO20',
        price: 499,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 459,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'RO30',
        price: 599,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 549,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'BIN8',
        price: 299,
        debris: ['Office', 'Food', 'Mix'],
        discountedPrice: 199,
        available: true,
        category: 'Bin',
        includedWeight: '',
        maxRentalPeriod: '',
      },
    ],
  },
  {
    id: 3,
    postalCode: 48094,
    city: 'Washington Township',
    territory: 'Detroit',
    state: 'Michigan',
    stateAbbreviation: 'MI',
    needsPermit: true,
    permitFee: 110,
    permitNotes: 'Prescheduled Pickup required',
    isFranchise: false,
    franchisePercentage: 0.0,
    overagePercentage: 0.089,
    products: [
      {
        sku: 'RO10',
        price: 459,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 409,
        available: true,
        category: 'Rolloff',
        includedWeight: 1000,
        maxRentalPeriod: 7,
      },
      {
        sku: 'RO20',
        price: 559,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 509,
        available: true,
        category: 'Rolloff',
        includedWeight: 2000,
        maxRentalPeriod: 14,
      },
      {
        sku: 'RO20C',
        price: 609,
        debris: ['Concrete'],
        discountedPrice: 559,
        available: true,
        category: 'Rolloff',
        includedWeight: 16000,
        maxRentalPeriod: 14,
      },

      {
        sku: 'RO30',
        price: 659,
        debris: ['Construction', 'Household', 'Mix'],
        discountedPrice: 609,
        available: true,
        category: 'Rolloff',
        includedWeight: 3000,
        maxRentalPeriod: 14,
      },
    ],
  },
]

export default productPricing
